BEGIN;

ALTER TABLE professions
ADD COLUMN IF NOT EXISTS submission_channel_id TEXT,
ADD COLUMN IF NOT EXISTS mission_title TEXT,
ADD COLUMN IF NOT EXISTS level_text TEXT,
ADD COLUMN IF NOT EXISTS difficulty_stars TEXT,
ADD COLUMN IF NOT EXISTS reward_text TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE clues
ADD COLUMN IF NOT EXISTS clue_title TEXT,
ADD COLUMN IF NOT EXISTS hint_text TEXT,
ADD COLUMN IF NOT EXISTS mission_type TEXT DEFAULT 'clue',
ADD COLUMN IF NOT EXISTS is_final BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE quest_runs
ADD COLUMN IF NOT EXISTS ticket_message_id TEXT,
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS abandoned_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS approved_by_admin_id TEXT,
ADD COLUMN IF NOT EXISTS completed_by_admin_id TEXT,
ADD COLUMN IF NOT EXISTS rejected_by_admin_id TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

COMMIT;
